### ISSUE TITLE
Please package sys-apps/xdg-desktop-portal-kde

### ISSUE THREAD

**Issue by devurandom** [fosero/flatpak-overlay#12]
Please package sys-apps/xdg-desktop-portal-kde from https://github.com/KDE/xdg-desktop-portal-kde and make it a USE=kde dependency of sys-apps/flatpak.

An Arch Linux PKGBUILD is available as a model: https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/xdg-desktop-portal-kde

**Comment by fosero** [comment]
Feel free to provide a pull-request, shouldn't be that much different from xdg-desktop-portal-gtk.

**Comment by seiflek** [comment]
Here's an example ebuild for it please review it cause i'm not into packaging kde stuff, i don't have a spare installation to test it, but i'll try to do it later.
[dpaste](http://dpaste.com/101F2JF)
