### ISSUE TITLE
Flatpak 1.0.1 fails to compile

### ISSUE THREAD

**Issue by divoxx** [fosero/flatpak-overlay#21]
It's currently failing to compile on my system. You can find emerge info and logs [here](https://gist.github.com/divoxx/575419c6a6063f1c25e8026904f272f4).

Let me know if I can provide any more details.

**Comment by divoxx** [comment]
By the way, this seems to be a patch fixing it on master: https://github.com/flatpak/flatpak/commit/e2a79a275dcaf5f19ea576b6ba87505a6d9b1566#diff-c30b5b79d6593bb04c975114faa5ebad

**Comment by fosero** [comment]
Thanks for the heads up, I added the patch to 1.0.1 .
I do wonder, in Gentoo the current version is 2.52, you really shouldn't be running such an outdated version.

**Comment by divoxx** [comment]
I run Gnome through the Gnome Without Systemd project (https://github.com/dantrell/gentoo-project-gnome-without-systemd) and they control stability separately based on the patches, which doesn't reflect latest stable Gnome in Gentoo with Systemd.

My system is as up-to-date as it can, apart from gnome :)

**Comment by divoxx** [comment]
By the way, thanks for the timely fix.
