### ISSUE TITLE
xdg-desktop-portal incompatibility with KDE overlay

### ISSUE THREAD

**Issue by leezu** [fosero/flatpak-overlay#27]
Hi @fosero, KDE overlay places packages as `x11-misc/xdg-desktop-portal` instead of `sys-apps/xdg-desktop-portal` used in your overlay. Do you think `x11-misc` is more appropriate? If so, please move teh ebuild in this repo. If not, please let me know and I'll file a bug with KDE overlay and ask them to rename.

**Comment by fosero** [comment]
There are no strict rules as to what belongs under a certain category. At the time I created this repo `sys-apps` seemed ok to me. Maybe `x11-misc` is a better place, could be.

This overlay is provided as single whole, not tied to any other overlay, other than the main repo. So for me, I do not need to change this. I wonder why the kde overlay provides `xdg-desktop-portal` anyway, if it does not provide flatpak to make use of it.

This would be more worth pursuing if the KDE team could back this request, up until such point I'll keep it as-is.

**Comment by leezu** [comment]
Thanks for your prompt reply @fosero. My concern is only that having your and KDE overlay activated leads breaks both, as some applications will depend on  `x11-misc/xdg-desktop-portal` while others depend on `sys-apps/xdg-desktop-portal`. Installing both is obviously impossible and emerge will abort during emerging whatever comes the second.

Of course you are free to keep your overlay incompatible to other overlays. It seems to me that KDE overlay is more "official" than yours however, as packages move from there directly to the main tree. So eventually, if noone argues for them to change the naming, `x11-misc/xdg-desktop-portal` may move to main tree.  I'm not involved in Gentoo KDE project. This is just to make you aware of the issues.

**Comment by leezu** [comment]
Regarding KDE overlays motivation to provide the desktop portal: It is mainly that Firefox 65 supports integration into KDE desktop via desktop-portal.
