### ISSUE TITLE
install fails to build due to systemd dependency

### ISSUE THREAD

**Issue by BTrey** [fosero/flatpak-overlay#31]
* Error: The above package list contains packages which cannot be
 * installed at the same time on the same system.

  (sys-apps/systemd-241-r1:0/2::gentoo, ebuild scheduled for merge) pulled in by
    sys-apps/systemd required by (virtual/service-manager-0:0/0::gentoo, installed)
    sys-apps/systemd:0= required by (sys-apps/dbus-1.12.12-r1:0/0::gentoo, ebuild scheduled for merge)
    sys-apps/systemd required by (sys-fs/libostree-2019.1:0/0::flatpak-overlay, ebuild scheduled for merge)
    >=sys-apps/systemd-207 required by (sys-apps/gentoo-systemd-integration-7:0/0::gentoo, ebuild scheduled for merge)
    sys-apps/systemd required by (virtual/tmpfiles-0:0/0::gentoo, installed)

  (sys-fs/eudev-3.2.5:0/0::gentoo, installed) pulled in by
    >=sys-fs/eudev-1.3:0/0[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?] (>=sys-fs/eudev-1.3:0/0[abi_x86_64(-)]) required by (virtual/libudev-232:0/1::gentoo, installed)
    >=sys-fs/eudev-2.1.1 required by (virtual/udev-217:0/0::gentoo, installed)

One of the reasons many people use Gentoo is because it's one of the few distributions which does not require systemd. If systemd is a hard dependency, then please add a note to the README which states that so that people don't waste their time adding the overlay and trying to install.

**Comment by fosero** [comment]
This is my personal overlay, provided as-is.

If you had even bothered to look through the issues, you would've seen #9. Which is the same thing and no-one stepped up to provide the needed changes yet, maybe you could?

**Comment by BTrey** [comment]
I would have no idea where to start making changes.  I suspect that it would require making changes to flatpak itself.  (That's based on attempts to install snapd, which is all but impossible without systemd.) But I didn't request you to fix the dependency on systemd.  I asked you to note it in the README file, because it is extremely common in the Gentoo community not to have systemd installed.  "This overlays requires installation of systemd."  Six words. That's it. It would probably have taken you less time to do that than it took you to post a snarky response. But you're right.  It IS your overlay. You do you. Thanks for contributing.
