### ISSUE TITLE
Fix Perms

### ISSUE THREAD

**Issue by KaMiila** [fosero/flatpak-overlay#33]
flatpak run org.gnome.FeedReader
bwrap: Creating new namespace failed, likely because the kernel does not support user namespaces.  bwrap must be installed setuid on such systems.
error: ldconfig failed, exit status 256

Fixed this error by changing perms.

chmod u+s /usr/libexec/flatpak-bwrap

**Comment by fosero** [comment]
Not sure what is going on here.

1. I don't think you should be changing permissions, it is probably a bad idea security wise. However the bwrap provided comes as suid afaik.
2. USER_NS should be in your kernel config as reported, check that you do have it. The ebuild checks for it as well, but if there is no kernel build around it will not fail on it I believe.

That being said, I am pretty sure this is a local problem.
