### ISSUE TITLE
Failed to get revokefs-fuse socket from system-helper: User flatpak does not exist in password file entry

### ISSUE THREAD

**Issue by realnc** [fosero/flatpak-overlay#35]
When I install something with flatpak, it says:

Warning: Failed to get revokefs-fuse socket from system-helper: User flatpak does not exist in password file entry

Upstream says this is a packaging bug:

https://github.com/flatpak/flatpak/issues/2959#issuecomment-504184253

**Comment by filmor** [comment]
This is not a packaging bug, this is missing documentation from upstream. There is already a pull request for this: #34

**Comment by fosero** [comment]
This got fixed in 1.4.2, thanks for the report.
