### ISSUE TITLE
flatpak & deps integration into Gentoo ::guru overlay

### ISSUE THREAD

**Issue by okias** [fosero/flatpak-overlay#39]
UPDATE:
Integration into `::guru` [1] overlay ongoing.

Goal of this step is:
- more regular updates,
- aligning ebuilds with Gentoo standards,
- better collaborations posibility
- availability inside layman overlays and
- potentially reaching ::gentoo portage.

All contributions are welcome! [2] (Changelog).
Feel free to review any Flatpak related packages and comment.

[1] https://wiki.gentoo.org/wiki/Project:GURU
[2] https://cgit.gentoo.org/repo/proj/guru.git/log/?h=dev

OLD:

Also I fixed #6 since, I send the pull request ;-)
I'll incorporate your email into pull request and you can simplify your Gentoo instructions!

Thank you for your work!

**Comment by okias** [comment]
@fosero please, in case you're against adding overlay into gentoo overlay list, just say it. It really would help to have your statement about that. If it's not issue for you, please provide email which can be associated with your overlay.

Thank you

**Comment by dev-0x7C6** [comment]
I was surprised that repository is not yet in repository list. I'll state some reasons to do so.

* Repository will get a Gentoo mirror with QA checks. 
* It'll be easier to setup repo by user just using eselect-repository
* Ebuild search engines (i.e. https://gpo.zugaina.org/) will help to find this overlay. (for some reason this repository is added as outside)

**Comment by okias** [comment]
@fosero kindly asking, would you provide your email for inclusion into layman?

**Comment by okias** [comment]
If fosero has no interest to offer his flatpak repository to users, I'll do mirror of this repository and add script to synchronize against fosero flatpak-overlay, I can't see any better way without @fosero interacting with us (users)

**Comment by gcarq** [comment]
Another option would be to add packages to the [GURU overlay](https://wiki.gentoo.org/wiki/Project:GURU).

**Comment by okias** [comment]
@gcarq thank you for the hint, it's happening :) feel free use this thread for upstreaming into ::guru discussion :)

Right now, slightly improved flatpak & deps is inside `::guru`

**Comment by gcarq** [comment]
@okias thank you very much. I'm already using it :) It might be worth to include the github mirror in this issue since it is also used for tracking issues and collaborating: https://github.com/gentoo/guru

**Comment by fosero** [comment]
I think I have made my stance around this abundantly clear, I am just interested in keeping a reasonable up-to-date flatpak repo for myself and maybe useful to others. I made it to scratch my own itch.

I have done the Gentoo developer thing a long time ago, I have no interest in further pursuing that or be part of some list or some side repo. Feel free to use whatever you can use from the repo, it is open source after all.

Now for a repo like Guru and the graveyard of many projects like it that have existed in the past: the lack of scope and guidelines will lead for it to falter at some point in the future. At random packages will be updated as maintainers come an go and interest rises and dwindles and there is no QA to speak of, so it will probably break randomly at times or create weird dependency issues with the main tree giving headaches to the real Gentoo devs dealing with bugreports. It would be better if you keep your repos small and to-the-point or even better if you would just join Gentoo and deal with the load of packages in the main tree that need updates and bug handling. I know the gnome herd could use some help.

**Comment by okias** [comment]
@fosero well, I asked you long time ago for email address to add your repo inside repositories (layman), but sadly without response, so I took flatpak inside ::guru to make it easy accesible for other users

**Comment by fosero** [comment]
As I said, I have no problem with that.

Guru's flatpak is already outdated and it seems xdg-desktop-portal never even got added. This has been like this for near 2 months it looks like. Some QA.

Using the Gentoo ostree, sure. It is also not kept up-to-date. You are really doing your users a favor here.

That is the problem with big overlays like guru; focus is the story of a decent repo. KISS

**Comment by gcarq** [comment]
@fosero It is fine if you don't want to get added to layman or collaborate on guru, but some things you pointed out are simply not true.

> At random packages will be updated as maintainers come an go and interest rises and dwindles and there is no QA to speak of

There is curated QA for commits. Packages also must pass `repoman -dx full`, which I can't say of this repo. Yes, packages are outdated from time to time, but so is this repo.

> it will probably break randomly at times or create weird dependency issues with the main tree giving headaches to the real Gentoo devs dealing with bugreports.

No, there are [rules](https://wiki.gentoo.org/wiki/Project:GURU#The_regulations) you have to follow when submitting a package. One explicitly says "Forking (overriding) actively maintained Gentoo packages into GURU is prohibited.".

> Guru's flatpak is already outdated and it seems xdg-desktop-portal never even got added. This has been like this for near 2 months it looks like. Some QA.

`sys-apps/xdg-desktop-portal` is already in `::gentoo`. This repo is also outdated on a regular base, and there were breaking issues for months. I don't demand anything, I just want to point out this has not necessarily to do with a size of an overlay.

Also if someone wants to add a package to gentoo, adding it to guru is the first step to achieve that.

**Comment by fosero** [comment]
This is going too far off-topic, thanks for your input. Please do stop posting your guru links here in every other issue/MR.
