### ISSUE TITLE
xdg-desktop-portal-1.6.0 missing in manifest

### ISSUE THREAD

**Issue by realnc** [fosero/flatpak-overlay#43]
Two issues here, really. One is that xdg-desktop-portal-1.6.0 is missing from the Manifest and thus emerge fails. The other is that this package already exists in portage (with what seems to be a newer ebuild), so I think this should be removed from the overlay altogether?

**Comment by fosero** [comment]
My bad, thanks for the report.

I might take the package in the main repo eventually over this one, but let's first see how well it gets updated.
