### ISSUE TITLE
sys-apps/flatpak: Use --with-system-bubblewrap

### ISSUE THREAD

**Issue by devurandom** [fosero/flatpak-overlay#46]
Gentoo has sys-apps/bubblewrap, so it seems like a good idea to use it for sys-apps/flatpak.

**Comment by fosero** [comment]
It is already quite outdated. I rather use bundled, it is kept up-to-date.

**Comment by marcthe12** [comment]
Could be a use flag.
On side note, is possibe @fosero to help maintain some of overlay package in the maintree like libostree, bublewrap, xdg-desktop portal. could reduce the efforts.

**Comment by fosero** [comment]
Could be a use-flag, but then I would use-flag it for users to have an outdated version. That seems not such a good idea, it is after all the sandbox.

If the upstream packages are well maintained I have no problem dropping them from this overlay, but as long that it is not the case I keep a copy for myself. I have no interest in becoming a Gentoo maintainer again, but I'm pretty sure they can use all the help offered :wink:
