### ISSUE TITLE
Segmentation faults everywhere with Flatpak 0.9.3

### ISSUE THREAD

**Issue by fusion809** [fosero/flatpak-overlay#7]
Hi,

Before today the last time I used Flatpaks to run apps was when 0.8.5 was still provided by this repo. Then Flatpaks worked fine but today since I upgraded to 0.9.3 I keep getting the error:

```bash
[1]    11922 segmentation fault  flatpak run org.gnome.Builder
```

whenever I try to launch GNOME Builder nightly with Flatpak (with `flatpak run org.gnome.Builder`). When I try to launch `com.xamarin.MonoDevelop` with Flatpak (using `flatpak run com.xamarin.MonoDevelop`) it fails giving the error message:

```bash
[1]    15686 segmentation fault  flatpak run com.xamarin.MonoDevelop
```

Thanks for your time,
Brenton

**Comment by fusion809** [comment]
Just installed `org.gnome.gedit` (Nightly) and tried to run it and it too returned a segmentation fault:

```bash
[1]    22213 segmentation fault  flatpak run org.gnome.gedit
```

**Comment by fusion809** [comment]
While building Flatpak no kernel config issues were found, in case you are wondering:

```bash
>>> Emerging (1 of 1) sys-apps/flatpak-0.9.2::flatpak-overlay
 * flatpak-0.9.2.tar.xz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                                                     [ ok ]
 * Determining the location of the kernel source code
 * Found kernel source directory:
 *     /usr/src/linux
 * Found kernel object directory:
 *     /lib/modules/4.10.12-gentoo/build
 * Found sources for kernel version:
 *     4.10.12-gentoo
 * Checking for suitable kernel configuration options...                                                                                         [ ok ]
```

**Comment by fosero** [comment]
It works fine for me. It could be interesting to examine the coredumps and see if there is a pattern.

Do you use system installed packages? The 0.9 release uses another directory for those, i included a check, but maybe it's incomplete?

Other than that I just package it, real bugs should be reported upstream.

**Comment by fusion809** [comment]
Well I'll open an issue at the upstream bugtracker, but I suspect this is Gentoo related, but I could be wrong.

**Comment by fosero** [comment]
Well, as said.. it could be literally anything, that's why you should check your coredumps first and the things I said.

How is this Gentoo related? Make sure it's not you related first.

**Comment by fusion809** [comment]
No I only use locally-installed Flatpak packages. That way it's easier to backup. Where would coredumps be?

**Comment by fosero** [comment]
If you use systemctl (and you probably are) there's coredumpctl, if not you can attach gdb to the process and get a stacktrace when it segfaults.
