### ISSUE TITLE
support openrc

### ISSUE THREAD

**Issue by grepwood** [fosero/flatpak-overlay#9]
I was quite astonished this package explicitly requires sys-apps/dbus with systemd

**Comment by fosero** [comment]
I haven't been using openrc for a very a long time, so there was little incentive to me and I am in no position to test it.

There is no explicit configure time switch to disable systemd support and flatpak does link to it (maybe through libostree), so feel free to provide a proper patch to implement this (for libostree as well).

**Comment by grepwood** [comment]
Hi, I took care of this myself. You just need to disable systemd USE in libostree. I'll provide a patch soon.

**Comment by fosero** [comment]
Note that it is not enough to just add it to the ebuild, it needs a fixed configure switch as well (as noted in the current ebuild). Otherwise it is not possible to disable systemd  (USE=-systemd) while systemd is installed on the system.

**Comment by SentToDevNull** [comment]
Fixed on my openrc install by adding "-systemd" as a global use flag. While this isn't a good option on systemd installs, one could modify the ebuilds to check the user's init system and add or delete the systemd use flag for the overlay's packages based on that.

**Comment by WizardUli** [comment]
@SentToDevNull There's no need to use global USE flag for this. Use _-systemd_ for _libostree_ only.

**Comment by fosero** [comment]
libostree has for a while already properly allowed systemd as an optional component. This was already available in the ebuild, but it was still marked as a preferred option. I've corrected this in 2019.2-r1.
